name: Secret WF

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  API_CSPROJ_PATH: ./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj

jobs:
  secrets:
    name: Secret Demo
    runs-on: ubuntu-latest

    steps:
      - name: Echo Environment Variable
        run: echo "$API_CSPROJ_PATH"
  
  new_job:
    name: New Secret Demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: another secret demo
    steps:
      - name: Echo Environment Variable
        run: echo "$JOB_NAME"
