name: Secret WF

on:
  workflow_dispatch:

env:
  API_CSPROJ_PATH: ./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj
jobs:
  secrets:
    name: Secret Demo
    runs-on: ubuntu-latest

    steps:
      - name: Echo Environment Variable
        run: echo "$API_CSPROJ_PATH"
